version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: gosnipit-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gosnipit
      # set these variables in a .env file in the root of the project
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./data:/var/lib/mysql